export const baseURL = 'http://localhost:3005/';
export const media = `${baseURL}media/`;
export const designs = `${baseURL}designs/`;
export const secretKey = 'fa#j)u=4ne88h+wqvy0%hwk=o8%tl(j4%(p=wa4_hzhcm#(8%x';
export const users = `${baseURL}users/`;
export const userSignin = `${users}signin/`;
export const logo = `${baseURL}media/logo.png`;
export const navImage = `${baseURL}media/navImage.jpg`;
export const designers = `${baseURL}designers/`;
